os: linux
language: python
python: "3.7"
dist: bionic
compiler:
  - gcc
  - g++
install:
  - pip install conan
  - conan user
  - conan remote add stiffstream https://api.bintray.com/conan/stiffstream/public
  - cmake --version
  - gcc --version
  - g++ --version
script:
  - conan install .
  - cmake . -G "Unix Makefiles"
  - cmake --build .