os: linux
matrix:
 - env:
   - WITH_BOOST=TRUE
 - env:
   - WITH_BOOST=FALSE
language: python
python: "3.7"
dist: bionic
compiler:
  - gcc
  - g++
install:
  - if [ "$WITH_BOOST" == "FALSE" ]; then sed -i "s;boost/1.73.0;;" conanfile.txt ; fi
  - pip install conan
  - conan user
  - conan remote add stiffstream https://api.bintray.com/conan/stiffstream/public
  - cmake --version
  - gcc --version
  - g++ --version
script:
  - conan install . --build=missing -s compiler.libcxx=libstdc++11
  - cmake . -G "Unix Makefiles"
  - cmake --build .