os: linux
language: python
python: "3.7"
dist: xenial
compiler:
  - gcc
  - g++
install:
  - pip install conan
  - conan user
  - conan remote add stiffstream https://api.bintray.com/conan/stiffstream/public
script:
  - conan install .
  - cmake . -G "Unix Makefiles"
  - cmake --build .